FROM python:3.13

# Optional: Set up a working directory
WORKDIR /workspace

# Optional: Install additional dependencies
# RUN pip install --upgrade pip

# Optional: Copy requirements.txt and install dependencies
# COPY requirements.txt ./
# RUN pip install -r requirements.txt
